### ISSUE TITLE
Public key used for credentials hashing

### ISSUE THREAD

**Issue by juanparati** [nordnet/nordnet-next-api#25]
Where can I download the public used for the "https://www.nordnet.se/api/2/login" endpoint.

According to the documentation have to hash the credentials in order to create a session (login), However the certificate is not available for download in the API documentation page (https://www.nordnet.dk/externalapi/docs/api).

I have a Nordnet account (DK) and I would like to use the API.

**Comment by IsaackRasmussen** [comment]
I was told by their support team earlier this year that they had cancelled the API for Danish users and had no plans to bring it back.

So for now, its probably only Sweden that has access.
